# Generated by Django 4.1 on 2022-09-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('width', models.FloatField()),
                ('Roll_no', models.FloatField()),
                ('Net_wt', models.FloatField()),
                ('Gr_wt', models.FloatField()),
                ('sell', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customer')),
                ('item_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.stock')),
            ],
        ),
    ]
