# Generated by Django 4.1 on 2022-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_stock_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sell_no',
            field=models.IntegerField(default=0),
        ),
    ]
