# Generated by Django 4.1 on 2022-09-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_stock_sell_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=60)),
            ],
        ),
    ]
