# Generated by Django 4.1 on 2022-09-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold',
            name='short_narration',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
