# Generated by Django 4.1 on 2022-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_sold_short_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='short_narration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
